
server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      
spring:
  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: cos
      password: cos1234
      jdbc-url: jdbc:mysql://localhost:3306/security?serverTimezone=Asia/Seoul
      #jdbc-url: jdbc:mysql://localhost:3306/security?serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    
  mvc:
    view:
      prefix: /templates/
      suffix: .mustache

  jpa:
    generate-ddl: false
    database: mysql
    properties:
      hibernate:
        use_sql_comments: true
        format_sql: true
    hibernate:
      ddl-auto: update #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
   
  thymeleaf:
    cache: false
  devtools:
    livereload:
      enabled: true
  

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 963678123238-do5mvrdjd5p3phheh2059m2q77a8mrhm.apps.googleusercontent.com
            client-secret: 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
            scope:
            - email
            - profile
